name: Run Postman Collection

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  newman:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run Postman Collection
        run: newman run https://github.com/z-zafirov/postman/blob/master/postman.sample.json
